/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsCategoryIndexRouteImport } from './routes/products.$category.index'
import { Route as ProductsCategoryProductRouteImport } from './routes/products.$category.$product'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryIndexRoute = ProductsCategoryIndexRouteImport.update({
  id: '/products/$category/',
  path: '/products/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryProductRoute = ProductsCategoryProductRouteImport.update({
  id: '/products/$category/$product',
  path: '/products/$category/$product',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/products/': typeof ProductsIndexRoute
  '/products/$category/$product': typeof ProductsCategoryProductRoute
  '/products/$category/': typeof ProductsCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/products': typeof ProductsIndexRoute
  '/products/$category/$product': typeof ProductsCategoryProductRoute
  '/products/$category': typeof ProductsCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/products/': typeof ProductsIndexRoute
  '/products/$category/$product': typeof ProductsCategoryProductRoute
  '/products/$category/': typeof ProductsCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/products/'
    | '/products/$category/$product'
    | '/products/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/products'
    | '/products/$category/$product'
    | '/products/$category'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/terms'
    | '/products/'
    | '/products/$category/$product'
    | '/products/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ProductsCategoryProductRoute: typeof ProductsCategoryProductRoute
  ProductsCategoryIndexRoute: typeof ProductsCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$category/': {
      id: '/products/$category/'
      path: '/products/$category'
      fullPath: '/products/$category/'
      preLoaderRoute: typeof ProductsCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$category/$product': {
      id: '/products/$category/$product'
      path: '/products/$category/$product'
      fullPath: '/products/$category/$product'
      preLoaderRoute: typeof ProductsCategoryProductRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ProductsCategoryProductRoute: ProductsCategoryProductRoute,
  ProductsCategoryIndexRoute: ProductsCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
